<a href="https://colab.research.google.com/github/divyaparadkar/DeepLearning_Traning/blob/main/Weston_healthcare_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow import keras
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler
from sklearn.utils.class_weight import compute_class_weight

In [ ]:
data=pd.read_csv('/content/watson_healthcare_modified.csv')

In [ ]:
data.head()

,EmployeeID,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,...,RelationshipSatisfaction,StandardHours,Shift,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,1313919,41,No,Travel_Rarely,1102,Cardiology,1,2,Life Sciences,1,...,1,80,0,8,0,1,6,4,0,5
1,1200302,49,No,Travel_Frequently,279,Maternity,8,1,Life Sciences,1,...,4,80,1,10,3,3,10,7,1,7
2,1060315,37,Yes,Travel_Rarely,1373,Maternity,2,2,Other,1,...,2,80,0,7,3,3,0,0,0,0
3,1272912,33,No,Travel_Frequently,1392,Maternity,3,4,Life Sciences,1,...,3,80,0,8,3,3,8,7,3,0
4,1414939,27,No,Travel_Rarely,591,Maternity,2,1,Medical,1,...,4,80,1,6,3,3,2,2,2,2

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1676 entries, 0 to 1675
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   EmployeeID                1676 non-null   int64
 1   Age                       1676 non-null   int64
 2   Attrition                 1676 non-null   object
 3   BusinessTravel            1676 non-null   object
 4   DailyRate                 1676 non-null   int64
 5   Department                1676 non-null   object
 6   DistanceFromHome          1676 non-null   int64
 7   Education                 1676 non-null   int64
 8   EducationField            1676 non-null   object
 9   EmployeeCount             1676 non-null   int64
 10  EnvironmentSatisfaction   1676 non-null   int64
 11  Gender                    1676 non-null   object
 12  HourlyRate                1676 non-null   int64
 13  JobInvolvement            1676 non-null   int64
 14  JobLevel                  1676 non-null   int64
 15  JobRole                   1676 non-null   object
 16  JobSatisfaction           1676 non-null   int64
 17  MaritalStatus             1676 non-null   object
 18  MonthlyIncome             1676 non-null   int64
 19  MonthlyRate               1676 non-null   int64
 20  NumCompaniesWorked        1676 non-null   int64
 21  Over18                    1676 non-null   object
 22  OverTime                  1676 non-null   object
 23  PercentSalaryHike         1676 non-null   int64
 24  PerformanceRating         1676 non-null   int64
 25  RelationshipSatisfaction  1676 non-null   int64
 26  StandardHours             1676 non-null   int64
 27  Shift                     1676 non-null   int64
 28  TotalWorkingYears         1676 non-null   int64
 29  TrainingTimesLastYear     1676 non-null   int64
 30  WorkLifeBalance           1676 non-null   int64
 31  YearsAtCompany            1676 non-null   int64
 32  YearsInCurrentRole        1676 non-null   int64
 33  YearsSinceLastPromotion   1676 non-null   int64
 34  YearsWithCurrManager      1676 non-null   int64
dtypes: int64(26), object(9)
memory usage: 458.4+ KB

In [ ]:
data.StandardHours.value_counts()

80    1676
Name: StandardHours, dtype: int64

In [ ]:
data.isna().sum()

EmployeeID                  0
Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
Shift                       0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

In [ ]:
data.drop(['DailyRate','HourlyRate','MonthlyRate','PercentSalaryHike','EmployeeID','Over18','EmployeeCount','StandardHours','RelationshipSatisfaction','PerformanceRating','WorkLifeBalance'],axis='columns',inplace=True)

In [ ]:
data.duplicated().sum()

56

In [ ]:
data.head()

,Age,Attrition,BusinessTravel,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,JobInvolvement,...,MonthlyIncome,NumCompaniesWorked,OverTime,Shift,TotalWorkingYears,TrainingTimesLastYear,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,No,Travel_Rarely,Cardiology,1,2,Life Sciences,2,Female,3,...,5993,8,Yes,0,8,0,6,4,0,5
1,49,No,Travel_Frequently,Maternity,8,1,Life Sciences,3,Male,2,...,5130,1,No,1,10,3,10,7,1,7
2,37,Yes,Travel_Rarely,Maternity,2,2,Other,4,Male,2,...,2090,6,Yes,0,7,3,0,0,0,0
3,33,No,Travel_Frequently,Maternity,3,4,Life Sciences,4,Female,3,...,2909,1,Yes,0,8,3,8,7,3,0
4,27,No,Travel_Rarely,Maternity,2,1,Medical,1,Male,3,...,3468,9,No,1,6,3,2,2,2,2

In [ ]:
column=['Attrition','OverTime']

In [ ]:
for col in column:
  data[col].replace({'Yes':1,'No':0},inplace=True)

In [ ]:
def col_unique(d):
  for col in d:
    print(col,":",d[col].unique())

In [ ]:
col_unique(data)

Age : [41 49 37 33 27 32 59 30 38 36 35 29 31 34 28 22 53 24 21 42 44 46 39 43
 50 26 48 55 45 56 23 51 40 54 58 20 25 19 57 52 47 18 60]
Attrition : [0 1]
BusinessTravel : ['Travel_Rarely' 'Travel_Frequently' 'Non-Travel']
Department : ['Cardiology' 'Maternity' 'Neurology']
DistanceFromHome : [ 1  8  2  3 24 23 27 16 15 26 19 21  5 11  9  7  6 10  4 25 12 18 29 22
 14 20 28 17 13]
Education : [2 1 4 3 5]
EducationField : ['Life Sciences' 'Other' 'Medical' 'Marketing' 'Technical Degree'
 'Human Resources']
EnvironmentSatisfaction : [2 3 4 1]
Gender : ['Female' 'Male']
JobInvolvement : [3 2 4 1]
JobLevel : [2 1 3 4 5]
JobRole : ['Nurse' 'Other' 'Therapist' 'Administrative' 'Admin']
JobSatisfaction : [4 2 3 1]
MaritalStatus : ['Single' 'Married' 'Divorced']
MonthlyIncome : [ 5993  5130  2090 ... 12742  9071  2836]
NumCompaniesWorked : [8 1 6 9 0 4 5 2 7 3]
OverTime : [1 0]
Shift : [0 1 3 2]
TotalWorkingYears : [ 8 10  7  6 12  1 17  5  3 31 13  0 26 24 22  9 19  2 23 14 15  4 29 28
 21 25 20 11 16 37 38 30 40 18 36 34 32 33 35 27]
TrainingTimesLastYear : [0 3 2 5 1 4 6]
YearsAtCompany : [ 6 10  0  8  2  7  1  9  5  4 25  3 12 14 22 15 27 21 17 11 13 37 16 20
 40 24 33 19 36 18 29 31 32 34 26 30 23]
YearsInCurrentRole : [ 4  7  0  2  5  9  8  3  6 13  1 15 14 16 11 10 12 18 17]
YearsSinceLastPromotion : [ 0  1  3  2  7  4  8  6  5 15  9 13 12 10 11 14]
YearsWithCurrManager : [ 5  7  0  2  6  8  3 11 17  1  4 12  9 10 15 13 16 14]

In [ ]:
data.head()

,Age,Attrition,BusinessTravel,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,JobInvolvement,...,MonthlyIncome,NumCompaniesWorked,OverTime,Shift,TotalWorkingYears,TrainingTimesLastYear,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,0,Travel_Rarely,Cardiology,1,2,Life Sciences,2,Female,3,...,5993,8,1,0,8,0,6,4,0,5
1,49,0,Travel_Frequently,Maternity,8,1,Life Sciences,3,Male,2,...,5130,1,0,1,10,3,10,7,1,7
2,37,1,Travel_Rarely,Maternity,2,2,Other,4,Male,2,...,2090,6,1,0,7,3,0,0,0,0
3,33,0,Travel_Frequently,Maternity,3,4,Life Sciences,4,Female,3,...,2909,1,1,0,8,3,8,7,3,0
4,27,0,Travel_Rarely,Maternity,2,1,Medical,1,Male,3,...,3468,9,0,1,6,3,2,2,2,2

In [ ]:
data.describe().T

,count,mean,std,min,25%,50%,75%,max
Age,1676.0,36.866348,9.129126,18.0,30.00,36.0,43.00,60.0
Attrition,1676.0,0.118735,0.323573,0.0,0.00,0.0,0.00,1.0
DistanceFromHome,1676.0,9.221957,8.158118,1.0,2.00,7.0,14.00,29.0
Education,1676.0,2.907518,1.025835,1.0,2.00,3.0,4.00,5.0
EnvironmentSatisfaction,1676.0,2.714797,1.097534,1.0,2.00,3.0,4.00,4.0
JobInvolvement,1676.0,2.724940,0.714121,1.0,2.00,3.0,3.00,4.0
JobLevel,1676.0,2.066826,1.113423,1.0,1.00,2.0,3.00,5.0
JobSatisfaction,1676.0,2.738663,1.104005,1.0,2.00,3.0,4.00,4.0
MonthlyIncome,1676.0,6516.512530,4728.456618,1009.0,2928.25,4899.0,8380.25,19999.0
NumCompaniesWorked,1676.0,2.662291,2.477704,0.0,1.00,2.0,4.00,9.0
OverTime,1676.0,0.284010,0.451076,0.0,0.00,0.0,1.00,1.0
Shift,1676.0,0.806086,0.855527,0.0,0.00,1.0,1.00,3.0
TotalWorkingYears,1676.0,11.338902,7.834996,0.0,6.00,10.0,15.00,40.0
TrainingTimesLastYear,1676.0,2.805489,1.288431,0.0,2.00,3.0,3.00,6.0
YearsAtCompany,1676.0,7.033413,6.098991,0.0,3.00,5.0,10.00,40.0
YearsInCurrentRole,1676.0,4.264916,3.627456,0.0,2.00,3.0,7.00,18.0
YearsSinceLastPromotion,1676.0,2.200477,3.229587,0.0,0.00,1.0,3.00,15.0
YearsWithCurrManager,1676.0,4.135442,3.559662,0.0,2.00,3.0,7.00,17.0

In [ ]:
data.corr()

<ipython-input-46-c44ded798807>:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  data.corr()

,Age,Attrition,DistanceFromHome,Education,EnvironmentSatisfaction,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,NumCompaniesWorked,OverTime,Shift,TotalWorkingYears,TrainingTimesLastYear,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
Age,1.000000,-0.239984,-0.010079,0.204655,0.008945,0.034193,0.518333,-0.015848,0.511378,0.296045,0.030970,0.037117,0.692512,-0.015408,0.319012,0.222655,0.217212,0.215909
Attrition,-0.239984,1.000000,0.105580,-0.038843,-0.101278,-0.166036,-0.207634,-0.081881,-0.193527,0.017279,0.337383,-0.158322,-0.234182,-0.054836,-0.201373,-0.207891,-0.086207,-0.201087
DistanceFromHome,-0.010079,0.105580,1.000000,0.015937,-0.019730,0.010281,-0.023455,-0.004758,-0.041201,-0.024969,0.038182,0.029180,-0.017663,-0.055471,-0.007420,0.011448,-0.000126,0.000403
Education,0.204655,-0.038843,0.015937,1.000000,-0.031925,0.041046,0.093227,-0.003957,0.085116,0.126758,-0.025776,0.024451,0.143324,-0.014070,0.057461,0.051029,0.045785,0.055096
EnvironmentSatisfaction,0.008945,-0.101278,-0.019730,-0.031925,1.000000,-0.007220,0.008277,0.001518,0.003372,0.012640,0.076885,0.005283,0.000208,-0.017722,-0.000448,0.012241,0.005866,-0.012417
JobInvolvement,0.034193,-0.166036,0.010281,0.041046,-0.007220,1.000000,-0.013660,-0.039738,-0.019240,0.016303,-0.014960,0.025999,-0.001576,-0.031580,-0.013652,0.020541,-0.022153,0.031574
JobLevel,0.518333,-0.207634,-0.023455,0.093227,0.008277,-0.013660,1.000000,-0.012497,0.951572,0.153179,0.006171,0.010478,0.780929,-0.004251,0.532529,0.387624,0.343102,0.379717
JobSatisfaction,-0.015848,-0.081881,-0.004758,-0.003957,0.001518,-0.039738,-0.012497,1.000000,-0.016550,-0.067204,0.017259,0.017740,-0.021435,-0.003440,0.005376,-0.001337,-0.013595,-0.023042
MonthlyIncome,0.511378,-0.193527,-0.041201,0.085116,0.003372,-0.019240,0.951572,-0.016550,1.000000,0.159062,0.011969,0.005847,0.772938,-0.009690,0.513977,0.364152,0.337241,0.350122
NumCompaniesWorked,0.296045,0.017279,-0.024969,0.126758,0.012640,0.016303,0.153179,-0.067204,0.159062,1.000000,-0.016159,0.023164,0.250514,-0.056122,-0.108807,-0.080578,-0.025033,-0.093030
OverTime,0.030970,0.337383,0.038182,-0.025776,0.076885,-0.014960,0.006171,0.017259,0.011969,-0.016159,1.000000,0.009751,0.019880,-0.080549,-0.018642,-0.042361,-0.027633,-0.049998
Shift,0.037117,-0.158322,0.029180,0.024451,0.005283,0.025999,0.010478,0.017740,0.005847,0.023164,0.009751,1.000000,0.009632,0.025881,0.013028,0.039263,0.011702,0.014314
TotalWorkingYears,0.692512,-0.234182,-0.017663,0.143324,0.000208,-0.001576,0.780929,-0.021435,0.772938,0.250514,0.019880,0.009632,1.000000,-0.026171,0.622495,0.457439,0.394941,0.461688
TrainingTimesLastYear,-0.015408,-0.054836,-0.055471,-0.014070,-0.017722,-0.031580,-0.004251,-0.003440,-0.009690,-0.056122,-0.080549,0.025881,-0.026171,1.000000,0.001739,-0.007362,-0.008844,-0.005057
YearsAtCompany,0.319012,-0.201373,-0.007420,0.057461,-0.000448,-0.013652,0.532529,0.005376,0.513977,-0.108807,-0.018642,0.013028,0.622495,0.001739,1.000000,0.759421,0.616915,0.771224
YearsInCurrentRole,0.222655,-0.207891,0.011448,0.051029,0.012241,0.020541,0.387624,-0.001337,0.364152,-0.080578,-0.042361,0.039263,0.457439,-0.007362,0.759421,1.000000,0.548235,0.721543
YearsSinceLastPromotion,0.217212,-0.086207,-0.000126,0.045785,0.005866,-0.022153,0.343102,-0.013595,0.337241,-0.025033,-0.027633,0.011702,0.394941,-0.008844,0.616915,0.548235,1.000000,0.518664
YearsWithCurrManager,0.215909,-0.201087,0.000403,0.055096,-0.012417,0.031574,0.379717,-0.023042,0.350122,-0.093030,-0.049998,0.014314,0.461688,-0.005057,0.771224,0.721543,0.518664,1.000000

In [ ]:
#  data.drop('PercentSalaryHike',inplace=True,axis=1)

In [ ]:
#  data.drop('PerformanceRating',inplace=True,axis=1)

In [ ]:
data['Gender'].replace({'Male':1,'Female':0},inplace=True)

In [ ]:
cols= ['BusinessTravel','Department','EducationField','MaritalStatus','JobRole']

In [ ]:
data=pd.get_dummies(data=data,columns=cols)

In [ ]:
data.head()

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1676 entries, 0 to 1675
Data columns (total 39 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Age                               1676 non-null   int64
 1   Attrition                         1676 non-null   int64
 2   DistanceFromHome                  1676 non-null   int64
 3   Education                         1676 non-null   int64
 4   EnvironmentSatisfaction           1676 non-null   int64
 5   Gender                            1676 non-null   int64
 6   JobInvolvement                    1676 non-null   int64
 7   JobLevel                          1676 non-null   int64
 8   JobSatisfaction                   1676 non-null   int64
 9   MonthlyIncome                     1676 non-null   int64
 10  NumCompaniesWorked                1676 non-null   int64
 11  OverTime                          1676 non-null   int64
 12  Shift                             1676 non-null   int64
 13  TotalWorkingYears                 1676 non-null   int64
 14  TrainingTimesLastYear             1676 non-null   int64
 15  YearsAtCompany                    1676 non-null   int64
 16  YearsInCurrentRole                1676 non-null   int64
 17  YearsSinceLastPromotion           1676 non-null   int64
 18  YearsWithCurrManager              1676 non-null   int64
 19  BusinessTravel_Non-Travel         1676 non-null   uint8
 20  BusinessTravel_Travel_Frequently  1676 non-null   uint8
 21  BusinessTravel_Travel_Rarely      1676 non-null   uint8
 22  Department_Cardiology             1676 non-null   uint8
 23  Department_Maternity              1676 non-null   uint8
 24  Department_Neurology              1676 non-null   uint8
 25  EducationField_Human Resources    1676 non-null   uint8
 26  EducationField_Life Sciences      1676 non-null   uint8
 27  EducationField_Marketing          1676 non-null   uint8
 28  EducationField_Medical            1676 non-null   uint8
 29  EducationField_Other              1676 non-null   uint8
 30  EducationField_Technical Degree   1676 non-null   uint8
 31  MaritalStatus_Divorced            1676 non-null   uint8
 32  MaritalStatus_Married             1676 non-null   uint8
 33  MaritalStatus_Single              1676 non-null   uint8
 34  JobRole_Admin                     1676 non-null   uint8
 35  JobRole_Administrative            1676 non-null   uint8
 36  JobRole_Nurse                     1676 non-null   uint8
 37  JobRole_Other                     1676 non-null   uint8
 38  JobRole_Therapist                 1676 non-null   uint8
dtypes: int64(19), uint8(20)
memory usage: 281.6 KB